3results page
iO-Academy/hotel-booking-system pull request #13
Opened 2017-11-29 11:37 UTC by trichoplax

2017-11-29 15:18 UTC, jturner11 requested changes
we want to see a message if all rooms are booked

2017-11-29 15:18 UTC, jturner11 commented on public/img/delete.svg
> +<g>
What do these spare <g> tags do? Should they be there?

2017-11-29 15:18 UTC, jturner11 commented on public/js/main.js
> +
remove white space

2017-11-29 15:18 UTC, jturner11 commented on public/js/resultsHandlebars.js
> +        if (v1 === v2) {
can you rename v1 & v2 to make them more semantic

2017-11-29 15:18 UTC, jturner11 commented on public/js/roomHandlebars.js
> +        if (v1 === v2) {
can we make these more semantic

2017-11-29 15:18 UTC, jturner11 commented on templates/index.phtml
> +                <input type="submit" class="date_submit" value="Book">
change book to search

2017-11-29 15:18 UTC, jturner11 commented on templates/index.phtml
> +        <p>Checkout</p>
change checkout to 'take a look'

2017-11-29 15:20 UTC, bennlongg commented on public/img/delete.svg
> +<g>
its an svg file, so i feel inclined to leave it how it was downloaded

2017-12-01 10:24 UTC, pdkoding commented on public/css/style.css
> +
empty line

2017-12-01 10:32 UTC, pdkoding requested changes
fix just one empty line pls

2017-12-01 11:54 UTC, merged